name: Deploy Static Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "tars90pct@gmail.com"
          git config --global user.name "tars90pct"
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/tars90pct/interview-notes.git

      - name: Run deploy:static script
        run: npm run deploy:static
